# docker-compose.yml

services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=formation
      - POSTGRES_PASSWORD=formationPassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
